#!/bin/sh
# --pancake 2010

if [ ! "$UID" = 0 ]; then
  echo "You need root."
  exit 1
fi

fs=10
img=image.ext2

# basic devices
cd _prefix
  mkdir -p dev/pts proc sys
  cd dev
    mknod -m 660 console c 5 1
    mknod -m 660 tty c 5 0
    mknod -m 660 null c 1 3
    mknod -m 660 zero c 1 5
  cd ..
cd ..

sz=$(printf %d $(du -hs _prefix|awk '{print $1}') 2>/dev/null)
sz=$(($sz+$fs))M
echo size=$sz

echo "creating raw disk in $img.. of $sz"
rm -f $img
# normal
#dd if=/dev/zero of=image.ext2 count=1 bs=$sz
# sparse
#dd if=/dev/zero of=$img bs=1k count=0 seek=$sz
truncate -s $sz $img

echo "creating ext2 image.."
yes | mke2fs $img

echo "copying contents from _prefix.."
mkdir -p .mnt
mount -o loop $img .mnt
cp -rfa _prefix/* .mnt
umount .mnt
sync
rm -rf .mnt

echo "done"

echo
echo 'qemu -kernel /tmp/bzImage -hda $img -append "root=/dev/sda init=/bin/dash"'
echo
