#!/bin/sh
# suckless package manager '2009-2010
# - pancake at nopcode dot org

function whereami {
  for a in $PWD `echo $PATH | sed 's,:, ,g'` ; do
    if [ -e "$a/$1" ]; then
      echo "$a/$1"
      break
    fi
  done
  echo $1
}
BIN="`readlink $0`"
[ -z "${BIN}" ] && BIN=$0
[ -z "${SHELL}" ] && BIN=/bin/sh
ARG0="`whereami $BIN`"
ROOT="`dirname $ARG0`"
USRDIR="${HOME}/.slpm"
WRKDIR="${ROOT}/_work"
PKGDIR="${ROOT}/pkg"
. "${ROOT}/config"
NFODIR="${DESTDIR}/${PREFIX}/var/lib/slpm/pkg"

function hg_fetch {
  mkdir -p $WRKDIR
  cd $WRKDIR
  if [ -d "$1" ]; then
    if [ "$3" = 1 ]; then
      echo "==> hg: updating $1 ..."
      ( cd "$1" ; hg pull && hg up )
    fi
  else
    hg clone "$2" "$1"
  fi
}

function git_fetch {
  mkdir -p "$WRKDIR"
  cd "$WRKDIR"
  if [ -d "$1" ]; then
    if [ "$3" = 1 ]; then
      ( cd "$1" ; git pull )
    fi
  else
    git clone "$2" "$1"
  fi
}

function tar_fetch {
  FILE="`basename $URL`"
  cd "$WRKDIR"
  if [ -f "$WRKDIR/$FILE" ]; then
    echo "==> Already downloaded $FILE"
  else
    wget -c $URL
  fi
  if [ -d "$WRKDIR/$PKG" ]; then
    echo "==> Already uncompressed and patched $PKG"
  else
    tar xzvf $FILE
  fi
}

function pkg_fetch {
  eval ${TYPE}_fetch $PKG $URL $1
}

function pkg_update {
  hg_fetch $PKG $URL
}

function pkg_build {
  if [ ! -d "$WRKDIR/$PKG" ]; then
    echo "pkg_build: Cannot open target directory"
    exit 1
  fi
  cd "$WRKDIR/$PKG"
  if [ -x "configure" ]; then
    ./configure "--prefix=${PREFIX}" ${CFGARGS} ${USER_CFGARGS}
  fi
  make "DESTDIR=${DESTDIR}" PREFIX=${PREFIX}
}

function pkg_install {
  if [ ! -d "$WRKDIR/$PKG" ]; then
    echo "pkg_install: Cannot open target directory"
    exit 1
  fi
  (
    cd "$WRKDIR/$PKG"
    make install DESTDIR=${DESTDIR} PREFIX=${PREFIX}
  )
  pkg_register
}

function pkg_register {
  [ -d "$NFODIR/$PKG" ] && return
  cd "$WRKDIR/$PKG"
  mkdir -p "${WRKDIR}/.tmp/${PKG}"
  make install "PREFIX=${WRKDIR}/.tmp/${PKG}"
  # go register
  mkdir -p "$NFODIR/$PKG"
  cd "${WRKDIR}/.tmp/${PKG}"
  find * -type f > "$NFODIR/$PKG/files"
  date > "$NFODIR/$PKG/date"
  rm -rf "${WRKDIR}/.tmp/${PKG}"
}

function pkg_clean {
  cd "$WRKDIR/$PKG"
  make clean
}

function pkg_deinstall {
  if [ -e "$NFODIR/$PKG/files" ]; then
    cd "${DESTDIR}/${PREFIX}"
    for a in `cat $NFODIR/$PKG/files`; do
      [ -f "$a" ] && echo "$a" && rm -f "$a"
    done
    rm -rf "$NFODIR/$PKG"
  else
    cd "$WRKDIR/$PKG"
    make uninstall DESTDIR=${DESTDIR} PREFIX=${PREFIX}
  fi
}

function help {
  echo "Usage: slpm [-iudlLx] [pkg pkg ..]"
  echo " -x : execute or enter into the slpm shell"
  echo " -u : upgrade package"
  echo " -i : install package"
  echo " -d : deinstall package"
  echo " -c : clean package"
  echo " -s : search package by keyword"
  echo " -l : list installed packages or pkg files"
  echo " -L : list all available packages"
  exit 1
}

[ ! -d "${NFODIR}" ] && mkdir -p "${NFODIR}"

DO=
while [ -n "$1" ]; do
  case "$1" in
  -x)
     SHELL=""
     [ -x "${PREFIX}/bin/sh" ] && SHELL="${PREFIX}/bin/sh"
     [ -x "${PREFIX}/bin/rc" ] && SHELL="${PREFIX}/bin/rc"
     if [ -z "${SHELL}" ]; then
       echo "Cannot find shell. Please install busybox or 9base"
       exit 1
     fi
     PATH=${PREFIX}/bin:${PREFIX}/sbin:${PATH}
     MANPATH=${PREFIX}/share/man:${MANPATH}
     LD_LIBRARY_PATH=${PREFIX}/lib:${LD_LIBRARY_PATH}
     PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}
     unset PROMPT_COMMAND
     export PATH MANPATH LD_LIBRARY_PATH PKG_CONFIG_PATH
     shift
     exec ${SHELL} $@
     ;;
  -h) help ; ;;
  -c|-i|-u|-d) DO=$1 ; ;;
  -s)
    if [ -z "$2" ]; then
      echo "Usage: slpm -s [keyword]"
    else
      cd ${PKGDIR} && grep DESC * | grep -i "$2"
    fi
    exit 0
    ;;
  -L) ls ${PKGDIR} | cat ; exit 0 ; ;;
  -l)
    if [ -z "$2" ]; then
      ls "$NFODIR" | cat ; exit 0
    else
      cat "$NFODIR/$2/files" ; exit 0
    fi
    ;;
  -*) echo "Unknown flag '$1'" ;;
  *) break ;;
  esac
  shift
done

function pkg_open {
  URL=""
  TYPE=""
  DESC=""
  DEPS=""
  CFGARGS=""
  . "${PKGDIR}/$1"
  if [ -e "${USRDIR}/$1" ]; then
    . "${USRDIR}/$1"
  fi
  # TODO: check package variables
  if [ -z "${URL}" ]; then echo "No URL defined in package"; fi
  if [ -z "${TYPE}" ]; then echo "No TYPE defined in package"; fi
}

[ -z "$1" ] && help
while [ -f "${PKGDIR}/$1" ] ; do
  PKG=$1
  pkg_open "${PKG}"
  case $DO in
  -c) (pkg_clean) ; ;;
  -i) (pkg_fetch) ; (pkg_build) ; (pkg_install) ; ;;
  -u) (pkg_fetch 1) ; (pkg_build) ; (pkg_install) ; ;;
  -d) (pkg_deinstall) ; ;;
  *) (pkg_fetch) ; ;;
  esac
  shift
done
